from ..basic import RetrosyntheticNode
from ..basic import RetrosyntheticPath
from ..configs import ValidationConfig


class PathCollapser:
    """Generates all valid collapsed variants of a retrosynthetic tree.

    A *collapsed* variant is produced by merging two consecutive steps:
    an intermediate molecule (internal node whose product is used as a
    reactant of another step) is removed, and the parent step directly
    inherits the reactants of the removed step.

    The constraint is that **no two adjacent steps** may be collapsed
    simultaneously, to prevent ambiguous or chemically meaningless
    merges.

    If the number of steps exceeds ``combination_step_limit``, only the
    original tree is returned (no variants are generated) to avoid
    combinatorial explosion.

    :param combination_step_limit: Maximum number of steps for which
        full combination enumeration is attempted.
    :type combination_step_limit: int
    """

    def __init__(
        self,
        combination_step_limit: int = ValidationConfig.combination_step_limit.value,
    ) -> None:
        """Initialize PathCollapser.

        :param combination_step_limit: Maximum number of steps before
            collapsing is skipped. Defaults to
            :attr:`ValidationConfig.combination_step_limit`.
        :type combination_step_limit: int
        """
        self._combination_step_limit = combination_step_limit

    def collapse(self, path: RetrosyntheticPath) -> tuple[RetrosyntheticPath, ...]:
        """Return all valid collapsed variants of ``path``.

        Always includes the original (uncollapsed) path. Additional
        variants are generated by merging non-adjacent skippable steps
        in every valid combination.

        :param path: The retrosynthetic path to collapse.
        :type path: RetrosyntheticPath

        :return: Tuple of path variants (original first, then collapsed
            variants in generation order, deduplicated by structure).
        :rtype: tuple[RetrosyntheticPath, ...]
        """
        if path.num_steps > self._combination_step_limit:
            return (path,)

        skippable = self._find_skippable_nodes(path)
        if not skippable:
            return (path,)

        adjacency = self._build_adjacency(path)
        combinations = self._generate_valid_combinations(skippable, adjacency)

        skippable_smiles = frozenset(n.canonical_smiles for n in skippable)
        descendants = self._build_descendant_map(path.root, skippable_smiles)

        seen: set[RetrosyntheticPath] = {path}
        result: list[RetrosyntheticPath] = [path]

        for combination in combinations:
            collapsed = self._apply_collapse(path, combination, descendants)
            if collapsed not in seen:
                seen.add(collapsed)
                result.append(collapsed)

        return tuple(result)

    def _build_descendant_map(
        self,
        root: RetrosyntheticNode,
        skippable_smiles: frozenset[str],
    ) -> dict[int, frozenset[str]]:
        """Map each node to the skippable SMILES present in its subtree.

        Lets :meth:`_rebuild_node` short-circuit (and avoid recursing into)
        subtrees that contain nothing from the current collapse set.

        :param root: Root node of the tree to index.
        :type root: RetrosyntheticNode
        :param skippable_smiles: Canonical SMILES of all skippable nodes.
        :type skippable_smiles: frozenset[str]

        :return: Mapping from ``id(node)`` to the frozenset of skippable
            canonical SMILES contained in that node's subtree.
        :rtype: dict[int, frozenset[str]]
        """
        mapping: dict[int, frozenset[str]] = {}

        def visit(node: RetrosyntheticNode) -> frozenset[str]:
            acc: set[str] = set()
            for child in node.children:
                acc |= visit(child)
                if child.canonical_smiles in skippable_smiles:
                    acc.add(child.canonical_smiles)
            result = frozenset(acc)
            mapping[id(node)] = result
            return result

        visit(root)
        return mapping

    def _build_adjacency(self, path: RetrosyntheticPath) -> dict[str, list[str]]:
        """Build a molecule-level adjacency map for the tree.

        Two nodes are adjacent when one node's molecule is a direct
        reactant of the other node's reaction.

        :param path: The retrosynthetic path to analyse.
        :type path: RetrosyntheticPath

        :return: Mapping from molecule SMILES to the list of adjacent
            molecule SMILES.
        :rtype: dict[str, list[str]]
        """
        adjacency: dict[str, list[str]] = {}

        for node in path.get_all_steps():
            node_smiles = node.canonical_smiles
            if node_smiles not in adjacency:
                adjacency[node_smiles] = []

            for child in node.children:
                if not child.children:
                    continue
                child_smiles = child.canonical_smiles
                if child_smiles not in adjacency:
                    adjacency[child_smiles] = []
                adjacency[node_smiles].append(child_smiles)
                adjacency[child_smiles].append(node_smiles)

        return adjacency

    def _find_skippable_nodes(
        self, path: RetrosyntheticPath
    ) -> tuple[RetrosyntheticNode, ...]:
        """Return all internal nodes eligible for collapsing.

        A node is *skippable* when its molecule appears as a reactant in
        at least one other step (i.e. it is an intermediate, not the
        target).

        :param path: The retrosynthetic path to analyse.
        :type path: RetrosyntheticPath

        :return: Tuple of skippable internal nodes.
        :rtype: tuple[RetrosyntheticNode, ...]
        """
        steps = path.get_all_steps()
        return tuple(n for n in steps if n is not path.root)

    def _generate_valid_combinations(
        self,
        skippable: tuple[RetrosyntheticNode, ...],
        adjacency: dict[str, list[str]],
    ) -> tuple[tuple[RetrosyntheticNode, ...], ...]:
        """Return all combinations of skippable nodes with no adjacencies.

        Uses backtracking to enumerate subsets of ``skippable`` such
        that no two nodes in a subset are adjacent according to
        ``adjacency``.

        :param skippable: Candidate nodes for collapsing.
        :type skippable: tuple[RetrosyntheticNode, ...]
        :param adjacency: Adjacency map from :meth:`_build_adjacency`.
        :type adjacency: dict[str, list[str]]

        :return: Tuple of valid node subsets, each subset being a tuple
            of nodes to collapse simultaneously.
        :rtype: tuple[tuple[RetrosyntheticNode, ...], ...]
        """
        results: list[tuple[RetrosyntheticNode, ...]] = []

        def backtrack(index: int, current: list[RetrosyntheticNode]) -> None:
            """Recursively enumerate valid non-adjacent subsets into ``results``.

            At each index, branches on whether to skip or include the
            candidate node; a node is only included when none of its
            molecule-adjacent neighbours are already present in
            ``current``.
            """
            if index == len(skippable):
                if current:
                    results.append(tuple(current))
                return

            backtrack(index + 1, current)

            node = skippable[index]
            adjacent = adjacency.get(node.canonical_smiles, [])
            can_include = all(c.canonical_smiles not in adjacent for c in current)
            if can_include:
                current.append(node)
                backtrack(index + 1, current)
                current.pop()

        backtrack(0, [])
        return tuple(results)

    def _apply_collapse(
        self,
        path: RetrosyntheticPath,
        combination: tuple[RetrosyntheticNode, ...],
        descendants: dict[int, frozenset[str]],
    ) -> RetrosyntheticPath:
        """Apply a collapse combination and return the modified path.

        For each node in ``combination``, removes it from the tree and
        replaces its molecule in the parent step's reactants with the
        node's own children.

        :param path: The original retrosynthetic path.
        :type path: RetrosyntheticPath
        :param combination: Nodes to collapse simultaneously.
        :type combination: tuple[RetrosyntheticNode, ...]
        :param descendants: Map from ``id(node)`` to the skippable SMILES
            in its subtree, from :meth:`_build_descendant_map`.
        :type descendants: dict[int, frozenset[str]]

        :return: A new :class:`RetrosyntheticPath` with the specified
            intermediates removed.
        :rtype: RetrosyntheticPath
        """
        to_collapse = frozenset(n.canonical_smiles for n in combination)
        new_root = self._rebuild_node(path.root, to_collapse, descendants)
        return RetrosyntheticPath(path_id=path.path_id, root=new_root)

    def _rebuild_node(
        self,
        node: RetrosyntheticNode,
        to_collapse: frozenset[str],
        descendants: dict[int, frozenset[str]],
    ) -> RetrosyntheticNode:
        """Rebuild ``node`` with every molecule in ``to_collapse`` bypassed.

        For any child whose canonical SMILES is in ``to_collapse``, its
        grandchildren are spliced into the current node's children in
        place; other children are recursed into unchanged.

        :param node: Subtree root to rebuild.
        :type node: RetrosyntheticNode
        :param to_collapse: Canonical SMILES of intermediate molecules
            to remove.
        :type to_collapse: frozenset[str]
        :param descendants: Map from ``id(node)`` to the skippable SMILES
            in its subtree, used to skip untouched subtrees.
        :type descendants: dict[int, frozenset[str]]

        :return: New subtree root with the chosen intermediates removed.
        :rtype: RetrosyntheticNode
        """
        if not node.children:
            return node
        # Nothing in this subtree is being collapsed: the result is
        # structurally identical, so reuse the immutable node and skip the
        # recursion entirely.
        if to_collapse.isdisjoint(descendants[id(node)]):
            return node
        new_children: list[RetrosyntheticNode] = []
        for child in node.children:
            if child.canonical_smiles in to_collapse:
                for grandchild in child.children:
                    new_children.append(
                        self._rebuild_node(grandchild, to_collapse, descendants)
                    )
            else:
                new_children.append(self._rebuild_node(child, to_collapse, descendants))
        return RetrosyntheticNode(smiles=node.smiles, children=tuple(new_children))
